# -*- coding: utf-8 -*-
"""Climate Change Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2OA4L0iFQumn9Qsg1N6ZNVtUcF61eWy
"""

import os
os.listdir()

import pandas as pd



df = pd.read_csv("global_climate_change_extreme_weather_2026.csv")
df.head()

df = pd.read_csv("global_climate_change_extreme_weather_2026.csv")
df.head()

df.info()

df.to_excel("climate_data.xlsx", index=False)

import pandas as pd

df_check = pd.read_excel("climate_data.xlsx")
df_check.head()

from google.colab import files

files.download("climate_data.xlsx")

import pandas as pd
import numpy as np

df = pd.read_excel("climate_data.xlsx")

df.head()

X = df[["year"]]

"""Define target variables, map qualitative to quantitative"""

dependent_variables = [
    "avg_temperature_c",
    "temperature_change_c",
    "co2_emissions_mt",
    "sea_level_rise_mm",
    "heatwave_days",
    "wildfire_incidents",
    "rainfall_change_mm",
    "air_quality_index",
    "flood_risk",
    "drought_risk"
]

risk_map = {
    "Low": 1,
    "Medium": 2,
    "High": 3
}

df["flood_risk"] = df["flood_risk"].map(risk_map)
df["drought_risk"] = df["drought_risk"].map(risk_map)

"""Train ML per Var"""

from sklearn.linear_model import LinearRegression

models = {}

for col in dependent_variables:
    model = LinearRegression()
    model.fit(X, df[col])
    models[col] = model

"""Create synthetic 2070 output"""

future = pd.DataFrame({"year": [2070] * len(df)})

"""Generate Syn data"""

synthetic = df.copy()
synthetic["year"] = 2070

for col in dependent_variables:
    synthetic[col] = models[col].predict(future)

"""Require increase in frequency of extreme events"""

for col in dependent_variables:
    synthetic[col] = models[col].predict(future)

"""Add noise"""

import numpy as np

for col in dependent_variables:
    synthetic[col] += np.random.normal(0, df[col].std() * 0.1, len(df))

"""Label Datasets"""

df["type"] = "Historical"

synthetic["type"] = "Synthetic_2070"

"""Combine Datasets"""

combine = pd.concat([df, synthetic], ignore_index=True)

combine.to_excel("climate_2070_dataset.xlsx", index=False)

from google.colab import files

files.download("climate_2070_dataset.xlsx")



























